---
  
- name: Restart the Cassandra service on all the Cassandra nodes
  hosts: cassandra
  gather_facts: false
  become_user: root
  become: true

  tasks:

    - name: Check Cassandra status
      shell: "netstat -tulpn | grep 7199"
      register: cas_status
      ignore_errors: true

    - block :

        - debug:
            msg: "Cassandra service currently RUNNING"

        - name: Shutting down Cassandra
          shell: "bin/shutdown_cassandra.sh"
          args:
            chdir: "/opt/simility/"

        - name: Starting Cassandra
          shell: "bin/startup_cassandra.sh &"
          args:
            chdir: "/opt/simility/"

        - name: Waiting for Cassandra to Startup
          wait_for:
            port: 7199
            delay: 3
            state: started
            timeout: 45
          register: port_check

        - debug:
            msg: "Successfully {{ port_check.state }} Cassandra"

      when: cas_status.stdout != ""


    - block :

        - debug:
            msg: "Cassandra service currently NOT RUNNING"

        - debug:
            msg: "Starting Cassandra"

        - name: Startup Cassandra
          shell: "bin/startup_cassandra.sh"
          args:
            chdir: "/opt/simility/"

        - name: Waiting for Cassandra to Startup
          wait_for:
            port: 7199
            delay: 3
            state: started
            timeout: 45
          register: port_check

        - debug:
            msg: "Successfully {{ port_check.state }} Cassandra"

      when: cas_status.stdout == ""


