---
  
- name: "Restart the {{ simility_service }} service on all the {{ simility_service }} nodes"
  hosts: target_hosts
  serial: 10
  gather_facts: false
  become_user: root
  become: true

  tasks:

  - block:

      - name: "Check {{ simility_service }} status"
        shell: "netstat -tulpn | grep 7199"
        register: cas_status
        ignore_errors: true

      - block :

          - debug:
              msg: "{{ simility_service }} service currently RUNNING"

          - name: "Shutting down {{ simility_service }}"
            shell: "bin/shutdown_{{ simility_service }}.sh"
            args:
              chdir: "/opt/simility/"

          - name: "Starting {{ simility_service }}"
            shell: "bin/startup_{{ simility_service }}.sh &"
            args:
              chdir: "/opt/simility/"

          - name: "Waiting for {{ simility_service }} to Startup"
            wait_for:
              port: 7199
              delay: 3
              state: started
              timeout: 45
            register: port_check

          - debug:
              msg: "Successfully {{ port_check.state }} {{ simility_service }}"

        when: cas_status.stdout != ""


      - block :

          - debug:
              msg: "{{ simility_service }} service currently NOT RUNNING"

          - debug:
              msg: "Starting {{ simility_service }}"

          - name: "Startup {{ simility_service }}"
            shell: "bin/startup_{{ simility_service }}.sh"
            args:
              chdir: "/opt/simility/"

          - name: "Waiting for {{ simility_service }} to Startup"
            wait_for:
              port: 7199
              delay: 3
              state: started
              timeout: 45
            register: port_check

          - debug:
              msg: "Successfully {{ port_check.state }} {{ simility_service }}"

        when: cas_status.stdout == "cassandra"

    
